---
abstract: 'Reimplementation of Device::SCSI with Moose.'
author:
  - 'potatogim <potatogim@potatogim.net>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Device-Moose-SCSI
no_index:
  directory:
    - t
    - inc
requires:
  Moose: '0'
  perl: '5.006'
version: '0.11'
